apiVersion: apps/v1
kind: Deployment
metadata:
  name: pigram-api-feed
  labels:
    app: pigram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pigram-api-feed
  template:
    metadata:
      labels:
        app: pigram-api-feed
    spec:
      containers:
        - name: pigram-api-feed
          image: ahmedbello/pigram-api-feed:v1
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_HOST
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_DB
                  optional: false
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_BUCKET
                  optional: false
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_REGION
                  optional: false
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_PROFILE
                  optional: false
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
                  optional: false
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: URL
                  optional: false
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
