apiVersion: v1
kind: Service
metadata:
  labels:
    app: pigram-api-feed
  name: pigram-api-feed-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/pigram-api-feed-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pigram-api-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
