version: "3"
services:
  reverseproxy:
    build:
      context: ./pigram-reverseproxy
    image: pigram-reverseproxy
  backend_user:
    build:
      context: ./pigram-api-user
    image: pigram-api-user
  backend_feed:
    build:
      context: ./pigram-api-feed
    image: pigram-api-feed
  frontend:
    build:
      context: ./pigram-frontend
    image: pigram-frontend:local