apiVersion: v1
kind: Service
metadata:
  labels:
    app: pigram-frontend
  name: pigram-frontend-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/pigram-frontend-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pigram-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
